---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: In order to get Ansible working, we need to install Python first (the snake bites itself)
      ansible.builtin.raw: apt update && apt install python3 -y
      register: install_python
      changed_when: install_python.stdout is search("The following NEW packages will be installed:") # implemeted for idempotence tests, see https://datamattsson.tumblr.com/post/186523898221/idempotence-and-changedwhen-with-ansible

    - name: Make sure python3 is installed
      ansible.builtin.package:
        name: python3
        state: present